project:
  type: website

website:
  title: "STA 113 2.0 Descriptive Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data.qmd
      - references.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

