---
title: "Group Assignment"
---

Date released: May 29, 2024

As part of your coursework, you will be working on a group assignment. This assignment will contribute 10% towards your final grade. Below are the details:

**1. Group Formation:**

-   You will be divided into groups of eight or nine members each. (For second-year students taking this unit this year, the group size will be fewer than eight.)

-   **Group Leader:** Select someone to lead your group and keep things organized.

-   **Secretary:** Another member should be designated as the secretary, tasked with maintaining detailed meeting minutes to track our discussions and decisions.

-   Further assign the following roles:

    -   Deputy leader (If the group size is less than 8, no need to have a deputy leader.)

    -   Assistant secretary

    -   Research Coordinator (Field 1 and History)

    -   Research Coordinator (Field 2 and Field 3)

    -   Research Coordinator (Field 4 and Field 5)

    -   Research Coordinator (Field 6 and Field 7 and Field 8) - appoint 2 students to this position.

**2. Assignment Task**

-   One member from each group will research and present the historical evolution of statistics.

-   The remaining members will each choose one field of application from the provided list and research the use of statistics in that field. The fields to choose from are:

    -   Field 1: Health Sciences
    -   Field 2: Business and Economics
    -   Field 3: Environmental Sciences
    -   Field 4: Social Sciences
    -   Field 5: Engineering
    -   Field 6: Education
    -   Field 7: Government and Public Policy
    -   Field 8: Information Technology

-   If your group has 8 members, you will work on History and Fields 1-7. If your group has 9 members, you will work on History and Fields 1-8. If your group has 6 members, you will work on History and Fields 1-5, and so on.

-   For each section content should be limited to 2 A4 page (you can use both sides of the pages) only, with font size 12 and Times New Roman.

**3. Submission Format:**

Submit the completed report as a single document following the specified format guidelines.

-   Cover page (Include group number)

-   Group members/ Index numbers/ Role/ Page contributed

-   Content:

    Title

    Content

    References

    Authors name

    Page number

-   Annexture

    -   Project timeline

    -   Meeting minutes

    -   Duties performed by the members (Assist the secretary in maintaining records and documentation, Ensure proper formatting and organization of the document, etc.)

**4. Submission deadline**

June 19, 2024

**You have been given a three-week timeframe to complete the assignment. Please begin work promptly to accommodate any unforeseen circumstances.**

This assignment provides an opportunity to deepen your understanding of statistical concepts and their practical applications while fostering teamwork and collaboration.

Every member should be familiar with the entire content of the report to ensure a comprehensive understanding

If you have any questions or require further clarification, please feel free to reach out to me (email: ttalagala\@sjp.ac.lk).

## Help desk

First help desk session will be held on June 5, 2024 from 3.15pm to 4.00pm.

If you need any additional support, please send an email to statdemos\@sci.sjp.ac.lk and reserve a time for a meeting (weekdays only between 8 a.m. and 4 p.m.).
