---
title: "STA 113 2.0 Descriptive Statistics"
---

## Lecturer-in-charge

### [Dr Thiyanga S. Talagala](https://thiyanga.netlify.app/)

## Email

ttalagala\@sjp.ac.lk

## Policies and regulations

To access important information regarding the unit STA 113 2.0 Descriptive Statistics, please go to the course Learning Management System (LMS) page. [**Click here**](https://lms.fas.sjp.ac.lk/enrol/index.php?id=3646) to go directly to the LMS. You must carefully read the "Course Information and Logistic" slide set for essential details. It is your responsibility to be aware of important details by thoroughly reviewing the "Course Information and Logistic" slides.

## Google Classroom

I also opened a Google Classroom as a backup strategy in case the LMS failed. Kindly ensure that you join it. The password is available on LMS under announcements.

## Course outline

Available on [**LMS**](https://lms.fas.sjp.ac.lk/enrol/index.php?id=3646)

## Weekly schedule

Here’s your roadmap for the semester!

### Week 1: April 24, 2024

**Slides 1.1:** [Course Information and Logistics](./week0/index.html)

**Slides 1.2:** [Definition of Statistics and Role of Statistics](./week1/index.html)

**Reading 1.1:** [American Statistical Association (ASA) Statement on The Role of Statistics in Data Science ...](https://www.amstat.org/docs/default-source/amstat-documents/the-role-of-statistics-in-data-science-and-artificial-intelligence.pdf)

**Exercise:** Find history of statistics.

### Week 2: May 15, 2024

**Slides 2:** [Basic Terminologies and Concepts in Statistics](./week2/index.html)

**Task:** Fill out the survey questionnaire available on the LMS.

### Week 3: May 22, 2024

**Slides 3:** [Data Collection](./Week3/index.html)

### Week 4: May 29, 2024

**Slides 4:** [Types and scales of measurement](./week4/index.html)

[Additional reading](https://www.statology.org/levels-of-measurement-nominal-ordinal-interval-and-ratio/)

Group assignment: 10%

### Week 5: June 5, 2024

**Slides 5:** [Analysing Categorical Data](./week5/index.html)

Tutorial 1: Group assignment help desk: 3.15PM - 4.00PM

### Week 6: June 10, 2024

**Slides 6:** [Analysing Categorical Data - Two-way graphs](./week6/index.html)

[Additional materials](./week5/tables.pdf)

### Week 7: June 12, 2024

**Slides 7:** [Frequency Distributions](./week7/index.html)

<!--[Additional Reading](https://statisticstechs.weebly.com/desciptive-statistics/frequency-distribution-and-data-presentation)-->

Tutorial 2: Please visit Google Classroom to view the tasks for the tutorials on Wednesday, June 12, 2024 from 3.15PM to 4PM.

### Week 8: June 19, 2024

**Slides 8:** [Measures of Central Tendency](./week8/index.html)

Note: Group assignment deadline is today.

Tutorial 3: Please visit Google Classroom to view the tasks for the tutorials on Wednesday, June 19, 2024 from 3.15PM to 4PM.

### Week 9/10: June 26, 2024/ June 28, 2024

**Slides 9:** [Stem and Leaf Plot, Dot plot, Individual value plot, Measures of Dispersion (Range, Variance, Standard deviation)](./week9/index.html)

Tutorial 4: June 26, 2024 from 3.15PM to 4PM.

Task: Week 7 slides 28-29 questions.

### Week 11: July 3, 2024

**Slides 10:** [More work on summary measures](./week10/index.html)

Tutorial 4: July 3, 2024 from 3.15PM to 4PM.

Please go to the Google Classroom to view the tasks.