---
title: "Individual Makeup Assignment"
---

Date released: July 29, 2024

Purpose: This assignment is for students who were unable to complete the group project due to late enrollment or other valid reasons.

This assignment will contribute 10% towards your final grade.

**Task:**

Select two fields from the following list and provide examples of statistical misuse in each:

    -   Field 1: Health Sciences
    -   Field 2: Business and Economics
    -   Field 3: Environmental Sciences
    -   Field 4: Social Sciences
    -   Field 5: Engineering
    -   Field 6: Education
    -   Field 7: Government and Public Policy
    -   Field 8: Information Technology
    

**Submission Guidelines:**

**Length:** Your assignment should be formatted to fit within two A4 sheets, which equates to four pages in total.

**Submission Platforms:** Please submit your completed assignment to both Google Classroom and the LMS.



**Submission deadline:**

August 8, 2024

It is the student’s responsibility to manage their time effectively to ensure that they have enough time to complete the assignment within the given timeframe. This includes allocating enough time to research, plan, and write the assignment, as well as allowing for unexpected circumstances or delays. It is important for students to plan their workload and prioritize their assignments to ensure that they are able to complete them on time and to the best of their ability.

**Late submission:** Submitting late work will be penalized by 1 mark per day. I will not accept any submissions after August 15, 2024.

**Extensions will be made in exceptional circumstances only.**

## Requesting a deadline extension

> You are allowed to apply for a deadline extension for the assignment under the following conditions only.

**Category A**

An illness that requires the student to miss all of his or her classes for 2 days or more.

**Category B**

A period of grief for the loss of a family member or friend.

**Category C**

A family emergency.

Valid documentation of proof is required **prior** to the assignment deadline.

The philosophy driving our late policy has three goals

-   Keep things fair.

-   Encourage good time management.

-   Encouragement and appreciation of on-time submission students.

**You have been given a 7 days timeframe to complete the assignment. Please begin work promptly to accommodate any unforeseen circumstances.**

If you have any questions or require further clarification, please feel free to reach out to me (email: ttalagala\@sjp.ac.lk).

## Help desk

Help desk session will be held on July 31, 2024 from 3.15pm to 4.00pm.

If you need any additional support, please send an email to statdemos\@sci.sjp.ac.lk and reserve a time for a meeting (weekdays only between 8 a.m. and 4 p.m.).


