---
title: "STA 113 2.0 Descriptive Statistics"
subtitle: "Bar Charts for Two Categorical Variables"
author: "Dr. Thiyanga S. Talagala <br/>  Department of Statistics, Faculty of Applied Sciences <br/> University of Sri Jayewardenepura, Sri Lanka"
format:
  revealjs:
    width: 2000
    height: 1000
    margin: 0.1
    theme: [simple, custom.scss]
    transition: slide
    background-transition: fade
    slide-number: true
    show-slide-number: all
    title-slide-attributes: 
      data-background-color: "#081d58"
      data-background-image: none
---

## Data Set

```{r, message=FALSE, warning=FALSE}
library(palmerpenguins)
library(tidyr)
library(dplyr)
library(ggplot2)
names(penguins)[names(penguins) == "sex"] <- "gender"
penguins_complete <- penguins |>
  drop_na()
quartiles <- quantile(penguins_complete$body_mass_g, probs = c(0.1, 0.5, 0.8))

pf <- penguins_complete |>
  mutate(BMI_category = case_when(
    body_mass_g <= quartiles[1] ~ "Underweight",
    body_mass_g > quartiles[1] & body_mass_g <= quartiles[2] ~ "Normal",
    body_mass_g > quartiles[2] & body_mass_g <= quartiles[3] ~ "Overweight",
    body_mass_g > quartiles[3] ~ "Obese"
  ))
pf2 <- pf |> select(species, island, gender, BMI_category)
pf2$BMI_category <- factor(pf2$BMI_category, levels=c("Underweight", "Normal",
"Overweight", "Obese"))

library(janitor)
# Create the two-way table
two_way_table <- pf2 |>
  count(species, BMI_category) |>
  spread(BMI_category, n, fill = 0) |>
  adorn_totals("row") |>
  adorn_totals("col") 

two_way_table |> knitr::kable()
```

# Grouped Bar Chart/ Clustered Bar Chart

##

```{r, fig.cap="Figure 1: Composition of the Sample by Species and BMI Category"}
pf2 |>
  count(species, BMI_category) |>
  complete(species = unique(species), BMI_category = unique(BMI_category), 
           fill = list(n = 0)) |>
  ggplot(aes(factor(species), n, fill = factor(BMI_category))) + 
  geom_bar(stat = 'identity', position = 'dodge') + labs(fill = "BMI Category", x="Species", y="Counts")

```

##


```{r, fig.cap="Figure 1: Composition of the Sample by Species and BMI Category"}
pf2 |>
  count(species, BMI_category) |>
  complete(species = unique(species), BMI_category = unique(BMI_category), 
           fill = list(n = 0)) |>
  ggplot(aes(factor(species), n, fill = factor(BMI_category))) + 
  geom_bar(stat = 'identity', position = 'dodge') + labs(fill = "BMI Category", x="Species", y="Counts") + scale_fill_manual(values = c("#91003f",  "#e7298a", "#d4b9da", "#bfd3e6"))

```

##


```{r, fig.cap="Figure 1: Composition of the Sample by Species and BMI Category"}
pf2 |>
  count(species, BMI_category) |>
  complete(species = unique(species), BMI_category = unique(BMI_category), 
           fill = list(n = 0)) |>
  ggplot(aes(factor(species), n, fill = factor(BMI_category))) + 
  geom_bar(stat = 'identity', position = 'dodge') + 
  geom_text(aes(label=n),  position = position_dodge(0.9),
                  vjust = 0, color = "black") + labs(fill = "BMI Category", x="Species", y="Counts") + scale_fill_manual(values = c("#91003f",  "#e7298a", "#d4b9da", "#bfd3e6"))

```

## Percentage Grouped Bar Chart

```{r}
pf2 <- pf2 %>%
  count(species, BMI_category) %>%
  complete(species = unique(pf2$species), BMI_category = unique(pf2$BMI_category), fill = list(n = 0)) %>%
  group_by(species) %>%
  mutate(row_percentage = n / sum(n) * 100) %>%
  ungroup()

# Plotting code for row percentages
ggplot(pf2, aes(x = factor(species), y = row_percentage, fill = factor(BMI_category))) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_text(aes(label = sprintf("%.1f%%", row_percentage)), 
            position = position_dodge(width = 0.9), vjust = -0.5, color = "black") +
  labs(fill = "BMI Category", x = "Species", y = "Percentage") +
  scale_fill_manual(values = c("#91003f", "#e7298a", "#d4b9da", "#bfd3e6")) +
  ylim(0, 100) +  # Ensure y-axis starts from 0 and ends at 100
  theme_minimal() 
```



##

https://afit-r.github.io/barcharts